# Generated by Django 4.2.3 on 2023-08-31 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personindexpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='personindexpage',
            name='strapline',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='is_senior',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='role',
        ),
    ]
