# Generated by Django 4.2.3 on 2023-09-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_remove_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
