# Generated by Django 4.2.3 on 2023-09-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(help_text='Write your message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='picture',
            field=models.ImageField(blank=True, help_text='Please upload a picture you would love to appear on the review', upload_to='reviews'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ratings',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], help_text='Please rate our services between 1 to 5', max_length=50),
        ),
    ]
