# Generated by Django 4.2.3 on 2023-09-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_message_alter_feedback_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='picture',
            field=models.ImageField(blank=True, help_text='Please upload a picture you would love to appear on the review', upload_to='reviews/'),
        ),
    ]
