# Generated by Django 4.2.3 on 2023-08-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpageauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='workpageauthor',
            name='page',
        ),
        migrations.RemoveField(
            model_name='workpagetagselect',
            name='page',
        ),
        migrations.RemoveField(
            model_name='workpagetagselect',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='workindexpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='workpage',
            name='body_word_count',
        ),
        migrations.RemoveField(
            model_name='workpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='workpage',
            name='client',
        ),
        migrations.RemoveField(
            model_name='workpage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workpage',
            name='homepage_image',
        ),
        migrations.RemoveField(
            model_name='workpage',
            name='listing_summary',
        ),
        migrations.RemoveField(
            model_name='workpage',
            name='related_services',
        ),
        migrations.RemoveField(
            model_name='workpage',
            name='visit_the_site',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='WorkPageAuthor',
        ),
        migrations.DeleteModel(
            name='WorkPageTagSelect',
        ),
    ]
