# Generated by Django 4.2.3 on 2023-09-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_thank_you_text_formpage_landing_page_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='use_other_template',
            field=models.BooleanField(blank=True, default=False, help_text='Use a different template', null=True, verbose_name='New Template'),
        ),
    ]
