# Generated by Django 4.2.3 on 2023-09-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_formpage_use_other_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='use_other_template',
            field=models.BooleanField(blank=True, default=False, help_text='Use a different template', verbose_name='New Template'),
        ),
    ]
