# Generated by Django 4.2.3 on 2023-08-17 21:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, default='www.instagram.com/', help_text='Instagram URL', max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, default='www.facebook.com/', help_text='Facebook URL', max_length=100, null=True)),
                ('twitter', models.URLField(blank=True, default='www.twitter.com/', help_text='Twitter URL', max_length=100, null=True)),
                ('pinterest', models.URLField(blank=True, default='www.pinterest.com/', help_text='Pinterest URL', max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, default='www.linkedin.com/', help_text='Linkedin URL', max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, default='Enter your WhatsApp number', help_text='Whatsapp Number', max_length=100, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Social Media Channel',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, help_text='Your website name', max_length=100, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('show_in_menu_bar', models.BooleanField(blank=True, default=False, help_text='Select to show logo in menu bar', verbose_name='Menu Logo')),
                ('show_title_in_menu_bar', models.BooleanField(blank=True, default=False, help_text='Select to show Title in menu bar', verbose_name='Menu Title')),
                ('api_key', models.CharField(blank=True, help_text='The API Key used for Google Maps', max_length=100, null=True, verbose_name='Google Maps API Key')),
                ('map_title', models.CharField(blank=True, help_text='Map Title for Screen readers, ex: Map to Goodale Park', max_length=100, null=True, verbose_name='Map Title')),
                ('place_id', models.CharField(blank=True, help_text='Requires API Key to use place ID', max_length=100, null=True, verbose_name='Google Place ID')),
                ('map_zoom_level', models.IntegerField(blank=True, help_text='Requires API Key to use zoom. 1: World, 5: Landmass/Continent, 10: City, 15: Streets, 20: Buildings', null=True, verbose_name='Map zoom level')),
                ('search', models.CharField(blank=True, help_text='Address or search term used to find your location on the map', max_length=250, verbose_name='Search')),
                ('shop_address', models.CharField(blank=True, help_text='Address or search term used to find your location on the map', max_length=250, verbose_name='Shop Address')),
                ('time_and_date', wagtail.fields.RichTextField(blank=True, verbose_name='Time and Day')),
                ('phone_no', models.CharField(blank=True, help_text='Your office phone number', max_length=250, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, help_text='Enter your email address', max_length=250, verbose_name='Email')),
                ('links', wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('code', wagtail.blocks.TextBlock(required=False))]))], blank=True, null=True, use_json_field=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('site_logo', models.ForeignKey(blank=True, help_text='Your website logo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Site Setting',
            },
        ),
    ]
