# Generated by Django 4.2.3 on 2023-08-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='shop_address',
            field=models.CharField(blank=True, default='Shop A7/A8 Ido Shopping Complex Apete Ibadan, Oyo State, Nigeria', help_text='Address or search term used to find your location', max_length=250, verbose_name='Shop Address'),
        ),
    ]
