# Generated by Django 4.2.3 on 2023-09-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_sitesettings_shop_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Setting'},
        ),
    ]
