# Generated by Django 4.2.3 on 2023-09-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sitesettings_head_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='head_links',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='links',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_links',
            field=models.TextField(blank=True, help_text='Use this to add links, scripts such as google analytics to the head section of the website', verbose_name='Links'),
        ),
    ]
