# Generated by Django 4.2.3 on 2023-09-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_remove_sitesettings_head_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, default='Genius multi-concept', help_text='Enter your facebook ID or name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, default='@genius', help_text='Enter your instagram username', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, default='@genius', help_text='Your linkedin username', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='pinterest',
            field=models.URLField(blank=True, default='@genius', help_text='pinterest username', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, default='@genius', help_text='Enter your twitter username', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='whatsapp',
            field=models.CharField(blank=True, default='Enter your WhatsApp number', help_text='Your whatsapp number', max_length=100, null=True),
        ),
    ]
